# Generated by Django 4.0.4 on 2022-04-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='productspecification',
            table='ProductSpecification',
        ),
        migrations.AlterModelTable(
            name='productspecificationvalue',
            table='ProductSpecificationValue',
        ),
        migrations.AlterModelTable(
            name='producttype',
            table='ProductType',
        ),
    ]
