# Generated by Django 4.0.4 on 2022-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=0, error_messages={'name': {'max_length': 'The price must be between o and 999.999.'}}, help_text='Maximum 999.99', max_digits=8, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=0, error_messages={'name': {'max_length': 'The price must be between o and 999.999.'}}, help_text='Maximum 999.99', max_digits=8, verbose_name='Regular Price'),
        ),
    ]
